### ISSUE TITLE
3. See One Movie — messy formatting & missing wireframe drawing

### ISSUE THREAD

**Issue by noltron000** [MakeSchool-Tutorials/Rotten-Potatoes-Part-Deux#10]
The tutorial mentions a wireframe drawing when one is not present.
> Now let's make the template. The template should look like this beautiful and masterful wireframe drawing

The 'show solution' nearby this has very little information or explanation.
> // movies.js

The code after the hint is not in code formatting.

The comment after the code _is_ in code formatting.

Just some messy things that needs cleaning up in this tutorial 👍

**Comment by ajbraus** [comment]
ahh this was a typo. Fixed!
