### ISSUE TITLE
3. See One Movie

### ISSUE THREAD

**Issue by alishalabi** [MakeSchool-Tutorials/Rotten-Potatoes-Part-Deux#11]
In the section where you create the movie-show.handlebars file, I was having an error where the form would not render once the route is called.

![image](https://user-images.githubusercontent.com/12772549/46036344-26ab2300-c0ba-11e8-81b9-8ab5e8353ad3.png)

In order to fix, I changed the "movie" from movie.poster_path, movie.overview, and movie.title to "movies":

![image](https://user-images.githubusercontent.com/12772549/46036566-aafda600-c0ba-11e8-8e34-b1534ce84995.png)

![image](https://user-images.githubusercontent.com/12772549/46036526-886b8d00-c0ba-11e8-940d-b35acf40d2dc.png)

**Comment by ajbraus** [comment]
Hmmm that's weird. I think you put movies instead of movie. But it is correct as it seems.
