### ISSUE TITLE
4. Associate Reviews to Movies — route confusion

### ISSUE THREAD

**Issue by noltron000** [MakeSchool-Tutorials/Rotten-Potatoes-Part-Deux#12]
> Adding Reviews to the Movie Show Template
> Don't forget about your reviews you already have. We're going to put those below the trailer.
> 
> First query them in the route.
> ```
> // movies.js
> 
> ...
> 
> app.get('/movies/:id', (req, res) => {
>   moviedb.movieInfo({ id: req.params.id }).then(movie => {
>     Review.find({ movieId: req.params.id }).then(reviews => {
>       res.render('movies-show', { movie: movie, reviews: reviews });
>     })
>   }).catch(console.error)
> })
> ```

The question is... which route? The show movie route? A new route? I was rather confused on this step, because my show route already has:
```
	app.get('/movies/:id', (req, res) => {
		moviedb.movieInfo({ id: req.params.id })
		.then(movie => {
			if (movie.video) {
				moviedb.movieVideos({ id: req.params.id })
				.then(videos => {
					console.log("TRAILER PASSED") //Checking pass/fail status
					movie.trailer_youtube_id = videos.results[0].key
					renderTemplate(movie)
				})
			} else {
				console.log("TRAILER FAILED") //Checking pass/fail status
				renderTemplate(movie)
			}
			function renderTemplate(movie) {
				res.render('movies-show', { movie: movie });
			}
		}).catch(console.error)
	})
```

So ultimately, I think this step could use some clarification to alleviate the confusion

**Comment by noltron000** [comment]
After putting that snippit above my existing code, it worked! This was not clear to me, and neither was the reasoning for this

**Comment by ajbraus** [comment]
good point, I'll make the snippet more clear.
