### ISSUE TITLE
4. Associate Reviews to Movies — movies-new.handlebars shouldn't exist(?)

### ISSUE THREAD

**Issue by noltron000** [MakeSchool-Tutorials/Rotten-Potatoes-Part-Deux#13]
> ```
> 
> 
> <form action="/movies/{{movieId}}/reviews">
> 
> ...
> 
> <input type="hidden" name="movieId" value="{{movieId}}">
> 
> ...
> 
> </form>
> ```

Notice how it says movies-new.handlebars...... I'm fairly sure it should be reviews-new.handlebars?

**Comment by ajbraus** [comment]
Fixed! Good catch!
