### ISSUE TITLE
5. Adding AJAX to Forms — smoke testing

### ISSUE THREAD

**Issue by noltron000** [MakeSchool-Tutorials/Rotten-Potatoes-Part-Deux#15]
I couldn't distinguish where I should put this code snippit:

>Then link it in the <head> tag of your layout like this.
>
>
>```
> <head>
>   ...
>   <script type="text/javascript" src="/javascript/scripts.js"></script>
>   ...
> </head>
> ```

The <head> tag — sure — but for which file?

**Comment by ajbraus** [comment]
Fixed. In the `main.handlebars` layout template. The <head></head> is the clue.
