### ISSUE TITLE
2. Seeing Movies — which directory?

### ISSUE THREAD

**Issue by noltron000** [MakeSchool-Tutorials/Rotten-Potatoes-Part-Deux#7]
Which directory do you create the "movies.js" file in?

Specifically, this part is not clear:
> "We are going to create a Movie resource, but it won't have a model or a collection, because the movies all live inside The MovieDB, but we will have a movies.js controller to house the Movie resource routes. We'll only need two movies routes:"

**Comment by noltron000** [comment]
It does seem that it says "movies.js controller" in this excerpt actually, but it'd be best if it was more clear in places like this. 👍

Example:
put movies.js in the controller directory

**Comment by ajbraus** [comment]
great!
