### ISSUE TITLE
2. Seeing Movies — res or req

### ISSUE THREAD

**Issue by noltron000** [MakeSchool-Tutorials/Rotten-Potatoes-Part-Deux#8]
It seems I needed to use **res**.render instead of **req**.render...although I am still not sure why this is 🙃

> When you go to Rotten Tomatoes, notice that the root route is not actually of reviews, it is of movies. We should do that too!
> 
> Let's comment out the / route in reviews.js and add a root route to our movies.js file
> 
> ```
> app.get('/', (req, res) => {
>   req.render('movies-index');
> })
> Now you'll need a movies-index.handlebars template with a little
> 
> <h1>Hello Movies</h1>
> ```
**req**.render('movies-index');

Please see bold text!

**Comment by ajbraus** [comment]
Fixed!
