### ISSUE TITLE
2. Seeing Movies — unclear adding poster image

### ISSUE THREAD

**Issue by noltron000** [MakeSchool-Tutorials/Rotten-Potatoes-Part-Deux#9]
Although the tutorial wants us to add a poster, it is unclear in exactly how to do so.
The closest I got was using {{this.poster_path}}

> Now that you've got this information make a thumbnail that displays the title and the poster. The thumbnail should be an <a> tag so it is clickable link to /movies/:id where the :id is the id provided from the API.

**Comment by ajbraus** [comment]
fixed!
